import rotateLogoImg from "../assets/img/rotateLogoImg.png";

export interface CoffeeChatListTypes {
  id: number;
  title: string;
  date: string;
  time: string;
  owner: string;
  currentUsers: number;
  maxUsers: number;
  desc: string;
  imgSrc: string;
}

export const COFFEE_CHAT_LIST_DUMMY = [
  {
    id: 1,
    title: "강남 프엔 번개 모임 강남 프엔 번개 모임",
    date: "2025-09-01",
    time: "14:00",
    owner: "김준희",
    currentUsers: 1,
    maxUsers: 10,
    desc: "프론트엔드 관련해서 여러가지 정보를 공유하는 방입니다! 도배글 작성 시 바로 강퇴합니다.",
    imgSrc: rotateLogoImg,
  },
  {
    id: 2,
    title: "역삼 프엔 번개 모임",
    date: "2025-09-02",
    time: "15:00",
    owner: "이수민",
    currentUsers: 2,
    maxUsers: 10,
    desc: "역삼에서 프론트엔드 관련 이야기를 나누는 모임입니다.",
    imgSrc: rotateLogoImg,
  },
  {
    id: 3,
    title: "홍대 프론트엔드 공부 모임",
    date: "2021-09-03",
    time: "16:00",
    owner: "박지훈",
    currentUsers: 3,
    maxUsers: 10,
    desc: "프론트엔드 공부하는 모임입니다. 좋은 정보 많이 공유해요.",
    imgSrc: rotateLogoImg,
  },
  {
    id: 4,
    title: "강남 JS 개발자 모임",
    date: "2021-09-04",
    time: "17:00",
    owner: "최민지",
    currentUsers: 4,
    maxUsers: 12,
    desc: "자바스크립트 개발자들끼리의 소규모 모임입니다.",
    imgSrc: rotateLogoImg,
  },
  {
    id: 5,
    title: "서울 프론트엔드 기술 모임",
    date: "2021-09-05",
    time: "18:00",
    owner: "이상훈",
    currentUsers: 5,
    maxUsers: 15,
    desc: "프론트엔드 관련 기술을 공유하는 모임입니다.",
    imgSrc: rotateLogoImg,
  },
  {
    id: 6,
    title: "기술 창업자들 모임",
    date: "2021-09-06",
    time: "19:00",
    owner: "김나영",
    currentUsers: 6,
    maxUsers: 20,
    desc: "스타트업 관련 기술 창업자들이 모이는 자리입니다.",
    imgSrc: rotateLogoImg,
  },
  {
    id: 7,
    title: "인공지능 프론트엔드 모임",
    date: "2021-09-07",
    time: "20:00",
    owner: "이동훈",
    currentUsers: 7,
    maxUsers: 12,
    desc: "AI와 프론트엔드의 결합을 논의하는 모임입니다.",
    imgSrc: rotateLogoImg,
  },
  {
    id: 8,
    title: "React 개발자 모임",
    date: "2021-09-08",
    time: "21:00",
    owner: "윤지현",
    currentUsers: 8,
    maxUsers: 15,
    desc: "React 관련 기술을 다루는 모임입니다.",
    imgSrc: rotateLogoImg,
  },
  {
    id: 9,
    title: "Vue.js 프론트엔드 모임",
    date: "2021-09-09",
    time: "10:00",
    owner: "박소영",
    currentUsers: 9,
    maxUsers: 15,
    desc: "Vue.js 프론트엔드 관련 정보와 기술을 다루는 모임입니다.",
    imgSrc: rotateLogoImg,
  },
  {
    id: 10,
    title: "Node.js 백엔드 모임",
    date: "2021-09-10",
    time: "11:00",
    owner: "정민호",
    currentUsers: 10,
    maxUsers: 15,
    desc: "Node.js를 사용하는 백엔드 개발자들의 모임입니다.",
    imgSrc: rotateLogoImg,
  },
  {
    id: 11,
    title: "프론트엔드 UX/UI 모임",
    date: "2021-09-11",
    time: "12:00",
    owner: "한지민",
    currentUsers: 11,
    maxUsers: 20,
    desc: "UX/UI 디자인과 프론트엔드를 결합하는 모임입니다.",
    imgSrc: rotateLogoImg,
  },
  {
    id: 12,
    title: "서울 웹 개발자 모임",
    date: "2021-09-12",
    time: "13:00",
    owner: "오세훈",
    currentUsers: 12,
    maxUsers: 15,
    desc: "서울에서 웹 개발 관련 이야기를 나누는 모임입니다.",
    imgSrc: rotateLogoImg,
  },
  {
    id: 13,
    title: "대전 프론트엔드 모임",
    date: "2021-09-13",
    time: "14:00",
    owner: "정유진",
    currentUsers: 13,
    maxUsers: 20,
    desc: "대전 지역에서 프론트엔드 개발을 논의하는 모임입니다.",
    imgSrc: rotateLogoImg,
  },
  {
    id: 14,
    title: "부산 개발자 모임",
    date: "2021-09-14",
    time: "15:00",
    owner: "최정호",
    currentUsers: 14,
    maxUsers: 20,
    desc: "부산에서 개발자들이 모여서 정보를 공유하는 모임입니다.",
    imgSrc: rotateLogoImg,
  },
  {
    id: 15,
    title: "전국 웹 개발자 모임",
    date: "2021-09-15",
    time: "16:00",
    owner: "김대희",
    currentUsers: 15,
    maxUsers: 25,
    desc: "전국 각지에서 웹 개발자들이 모여서 경험을 공유하는 자리입니다.",
    imgSrc: rotateLogoImg,
  },
];
