import type { ScheduleBlockProps } from "../types/ScheduleTypes";

export const SCHEDULES_DUMMY: ScheduleBlockProps[] = [
  {
    id: 1,
    title: "강남 프엔 번개모임",
    location: "서울시 강남구 역삼로",
    locationDetail: "강남역 6번 출구 신분당선 앞",
    date: "2025-02-20",
    startTime: "오후 6:30",
    endTime: "오후 9:00",
  },
  {
    id: 2,
    title: "코스티 프로젝트 회의",
    location: "코스터 사무실",
    locationDetail: "서울 강남구 테헤란로 123",
    date: "2025-02-25",
    startTime: "오전 10:00",
    endTime: "오후 12:00",
  },
  {
    id: 3,
    title: "해커톤 팀 미팅",
    location: "온라인 (Zoom)",
    locationDetail: "링크 개별 전달",
    date: "2025-03-05",
    startTime: "오후 8:00",
    endTime: "오후 10:00",
  },
  {
    id: 4,
    title: "코스티 프로젝트 회의",
    location: "코스터 사무실",
    locationDetail: "서울 강남구 테헤란로 123",
    date: "2025-02-25",
    startTime: "오전 10:00",
    endTime: "오후 12:00",
  },
  {
    id: 5,
    title: "해커톤 팀 미팅",
    location: "온라인 (Zoom)",
    locationDetail: "링크 개별 전달",
    date: "2025-03-05",
    startTime: "오후 8:00",
    endTime: "오후 10:00",
  },
  {
    id: 6,
    title: "코스티 프로젝트 회의",
    location: "코스터 사무실",
    locationDetail: "서울 강남구 테헤란로 123",
    date: "2025-02-25",
    startTime: "오전 10:00",
    endTime: "오후 12:00",
  },
  {
    id: 7,
    title: "해커톤 팀 미팅",
    location: "온라인 (Zoom)",
    locationDetail: "링크 개별 전달",
    date: "2025-03-05",
    startTime: "오후 8:00",
    endTime: "오후 10:00",
  },
];
